version: "3.7"

services:

  mail:
    image: mailhog/mailhog
    container_name: main_mh
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=main_vpcbr"
      - "traefik.http.routers.mail.entrypoints=web"
      - "traefik.http.routers.mail.rule=Host(`mailhog.develop.eu`)"
      - "traefik.http.routers.mail.service=mail"
      - "traefik.http.services.mail.loadbalancer.server.port=8025"
    #env_file: ./env/common.env
    networks:
      main_vpcbr:
        ipv4_address: 11.88.0.16
        aliases:
          - mailhog.develop.eu

  portainer:
    container_name: main_portainer
    image: portainer/portainer
    restart: always
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=main_vpcbr"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.routers.portainer.rule=Host(`portainer.develop.eu`)"
    networks:
      main_vpcbr:
        ipv4_address: 11.88.0.3

  traefik:
    container_name: main_traefik
    image: 'traefik:v2.4'
    restart: always
    # command: -c /dev/null --web --docker --logLevel=INFO
    security_opt:
      - no-new-privileges:true
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker_package/traefik/traefik.yml:/traefik.yml:ro
      - ./docker_package/traefik/acme.json:/acme.json
      - ./docker_package/traefik/acme-dns:/acme-dns
       # Add folder with dynamic configuration yml
      - ./docker_package/traefik/configurations:/configurations
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=main_vpcbr"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.rule=Host(`traefik.develop.eu`)"
      - "traefik.http.routers.traefik.middlewares=user-auth@file"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=le-dns"
      - "traefik.http.routers.traefik.tls.domains[0].main=develop.eu"
      - "traefik.http.routers.traefik.tls.domains[0].sans=*.develop.eu"
    environment:
      - ACME_DNS_API_BASE=https://auth.acme-dns.io
      - ACME_DNS_STORAGE_PATH=/acme-dns
    networks:
      main_vpcbr:
        ipv4_address: 11.88.0.2

networks:
  main_vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 11.88.0.0/16
          gateway: 11.88.0.1

